export const skills = [
  { "label": "HTML", "value": "HTML" },
  { "label": "CSS", "value": "CSS" },
  { "label": "JavaScript", "value": "JavaScript" },
  { "label": "TypeScript", "value": "TypeScript" },
  { "label": "React", "value": "React" },
  { "label": "Next.js", "value": "Next.js" },
  { "label": "Vue.js", "value": "Vue.js" },
  { "label": "Nuxt.js", "value": "Nuxt.js" },
  { "label": "Angular", "value": "Angular" },
  { "label": "Svelte", "value": "Svelte" },
  { "label": "SolidJS", "value": "SolidJS" },
  { "label": "Tailwind CSS", "value": "Tailwind CSS" },
  { "label": "Bootstrap", "value": "Bootstrap" },
  { "label": "Sass", "value": "Sass" },
  { "label": "Less", "value": "Less" },
  { "label": "Node.js", "value": "Node.js" },
  { "label": "Express", "value": "Express" },
  { "label": "NestJS", "value": "NestJS" },
  { "label": "Fastify", "value": "Fastify" },
  { "label": "PHP", "value": "PHP" },
  { "label": "Laravel", "value": "Laravel" },
  { "label": "Symfony", "value": "Symfony" },
  { "label": "CodeIgniter", "value": "CodeIgniter" },
  { "label": "WordPress", "value": "WordPress" },
  { "label": "Django", "value": "Django" },
  { "label": "Flask", "value": "Flask" },
  { "label": "FastAPI", "value": "FastAPI" },
  { "label": "Python", "value": "Python" },
  { "label": "Ruby", "value": "Ruby" },
  { "label": "Rails", "value": "Rails" },
  { "label": "Sinatra", "value": "Sinatra" },
  { "label": "Java", "value": "Java" },
  { "label": "Spring Boot", "value": "Spring Boot" },
  { "label": "Kotlin", "value": "Kotlin" },
  { "label": "Scala", "value": "Scala" },
  { "label": "Groovy", "value": "Groovy" },
  { "label": "C", "value": "C" },
  { "label": "C++", "value": "C++" },
  { "label": "C#", "value": "C#" },
  { "label": ".NET", "value": ".NET" },
  { "label": "ASP.NET Core", "value": "ASP.NET Core" },
  { "label": "Go", "value": "Go" },
  { "label": "Rust", "value": "Rust" },
  { "label": "Swift", "value": "Swift" },
  { "label": "Objective-C", "value": "Objective-C" },
  { "label": "Dart", "value": "Dart" },
  { "label": "Flutter", "value": "Flutter" },
  { "label": "React Native", "value": "React Native" },
  { "label": "Ionic", "value": "Ionic" },
  { "label": "Xamarin", "value": "Xamarin" },
  { "label": "Android SDK", "value": "Android SDK" },
  { "label": "iOS SDK", "value": "iOS SDK" },
  { "label": "SQL", "value": "SQL" },
  { "label": "PostgreSQL", "value": "PostgreSQL" },
  { "label": "MySQL", "value": "MySQL" },
  { "label": "MariaDB", "value": "MariaDB" },
  { "label": "SQLite", "value": "SQLite" },
  { "label": "Oracle", "value": "Oracle" },
  { "label": "MongoDB", "value": "MongoDB" },
  { "label": "Redis", "value": "Redis" },
  { "label": "Cassandra", "value": "Cassandra" },
  { "label": "DynamoDB", "value": "DynamoDB" },
  { "label": "GraphQL", "value": "GraphQL" },
  { "label": "Apollo", "value": "Apollo" },
  { "label": "Relay", "value": "Relay" },
  { "label": "REST API", "value": "REST API" },
  { "label": "gRPC", "value": "gRPC" },
  { "label": "WebSockets", "value": "WebSockets" },
  { "label": "Docker", "value": "Docker" },
  { "label": "Kubernetes", "value": "Kubernetes" },
  { "label": "Terraform", "value": "Terraform" },
  { "label": "Ansible", "value": "Ansible" },
  { "label": "AWS", "value": "AWS" },
  { "label": "Azure", "value": "Azure" },
  { "label": "Google Cloud Platform", "value": "Google Cloud Platform" },
  { "label": "Firebase", "value": "Firebase" },
  { "label": "Supabase", "value": "Supabase" },
  { "label": "Heroku", "value": "Heroku" },
  { "label": "Netlify", "value": "Netlify" },
  { "label": "Vercel", "value": "Vercel" },
  { "label": "Linux", "value": "Linux" },
  { "label": "Bash", "value": "Bash" },
  { "label": "PowerShell", "value": "PowerShell" },
  { "label": "Git", "value": "Git" },
  { "label": "GitHub", "value": "GitHub" },
  { "label": "GitLab", "value": "GitLab" },
  { "label": "Bitbucket", "value": "Bitbucket" },
  { "label": "CI/CD", "value": "CI/CD" },
  { "label": "Jenkins", "value": "Jenkins" },
  { "label": "GitHub Actions", "value": "GitHub Actions" },
  { "label": "CircleCI", "value": "CircleCI" },
  { "label": "Travis CI", "value": "Travis CI" },
  { "label": "Webpack", "value": "Webpack" },
  { "label": "Vite", "value": "Vite" },
  { "label": "Parcel", "value": "Parcel" },
  { "label": "Rollup", "value": "Rollup" },
  { "label": "Babel", "value": "Babel" },
  { "label": "ESLint", "value": "ESLint" },
  { "label": "Prettier", "value": "Prettier" },
  { "label": "Testing Library", "value": "Testing Library" },
  { "label": "Jest", "value": "Jest" },
  { "label": "Mocha", "value": "Mocha" },
  { "label": "Chai", "value": "Chai" },
  { "label": "Cypress", "value": "Cypress" },
  { "label": "Playwright", "value": "Playwright" },
  { "label": "Selenium", "value": "Selenium" },
  { "label": "Puppeteer", "value": "Puppeteer" },
  { "label": "Storybook", "value": "Storybook" },
  { "label": "Figma", "value": "Figma" },
  { "label": "UI/UX Design", "value": "UI/UX Design" },
  { "label": "Redux", "value": "Redux" },
  { "label": "Redux Toolkit", "value": "Redux Toolkit" },
  { "label": "RTK Query", "value": "RTK Query" },
  { "label": "Zustand", "value": "Zustand" },
  { "label": "MobX", "value": "MobX" },
  { "label": "Recoil", "value": "Recoil" },
  { "label": "RxJS", "value": "RxJS" },
  { "label": "Three.js", "value": "Three.js" },
  { "label": "D3.js", "value": "D3.js" },
  { "label": "Chart.js", "value": "Chart.js" },
  { "label": "ECharts", "value": "ECharts" },
  { "label": "WebAssembly", "value": "WebAssembly" },
  { "label": "WebRTC", "value": "WebRTC" },
  { "label": "PWA", "value": "PWA" },
  { "label": "Service Workers", "value": "Service Workers" },
  { "label": "OAuth", "value": "OAuth" },
  { "label": "JWT", "value": "JWT" },
  { "label": "OpenAPI (Swagger)", "value": "OpenAPI (Swagger)" },
  { "label": "Postman", "value": "Postman" },
  { "label": "Insomnia", "value": "Insomnia" },
  { "label": "RabbitMQ", "value": "RabbitMQ" },
  { "label": "Kafka", "value": "Kafka" },
  { "label": "Nginx", "value": "Nginx" },
  { "label": "Apache", "value": "Apache" },
  { "label": "Vagrant", "value": "Vagrant" },
  { "label": "VirtualBox", "value": "VirtualBox" },
  { "label": "VMware", "value": "VMware" },
  { "label": "Shell Scripting", "value": "Shell Scripting" },
  { "label": "MATLAB", "value": "MATLAB" },
  { "label": "R", "value": "R" },
  { "label": "Julia", "value": "Julia" },
  { "label": "Perl", "value": "Perl" },
  { "label": "Haskell", "value": "Haskell" },
  { "label": "Elixir", "value": "Elixir" },
  { "label": "Phoenix", "value": "Phoenix" },
  { "label": "Clojure", "value": "Clojure" },
  { "label": "F#", "value": "F#" },
  { "label": "Assembly", "value": "Assembly" },
  { "label": "COBOL", "value": "COBOL" },
  { "label": "Fortran", "value": "Fortran" },
  { "label": "Solidity", "value": "Solidity" },
  { "label": "Web3.js", "value": "Web3.js" },
  { "label": "Ethers.js", "value": "Ethers.js" },
  { "label": "Blockchain", "value": "Blockchain" },
  { "label": "Smart Contracts", "value": "Smart Contracts" },
  { "label": "Rust (Solana)", "value": "Rust (Solana)" },
  { "label": "Hardhat", "value": "Hardhat" },
  { "label": "Truffle", "value": "Truffle" },
  { "label": "Foundry", "value": "Foundry" }
]
